name: Release NPCs Go Home
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: "NPCs-Go-Home"
    steps:
      - name: Checkout Master
        uses: actions/checkout@v5
        with:
          fetch-depth: 50

      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: ${{env.ARCHIVE_NAME}}.zip
          exclusions: "*.git*"

      - name: Release
        uses: docker://antonyurchenko/git-release:v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME_PREFIX: "Release "
          # ALLOW_EMPTY_CHANGELOG: true
        with:
          args: |
            ${{env.ARCHIVE_NAME}}.zip
